FROM golang:1.25.7

LABEL maintainer="Richard Knop <risoknop@gmail.com>"

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    gcc \
    libc6-dev \
    libsqlite3-dev \
    make \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=1

CMD ["make", "test-with-coverage"]
